import { wait } from "@testing-library/user-event/dist/utils";
import { URLS } from "../../src/routes";

describe("Company Page", () => {
    beforeEach(() => {
        cy.login()
        cy.visit("http://localhost:3000/" + URLS.DASHBOARD.COMPANY.LIST)
    })

    it("company page => render block", () => {
        cy.get('[data-testid="common-block"]').should('have.length', 1)
    })

    it("company page => add new company => input correct data", () => {
        // ovaj test pada ako vec ima kompanija sa maticnim brojem 1111111111111
        // tako da je najbolje da se test izvrsi tek nakon sto se pokrene back
        cy.get('[data-testid="common-button"]')
            .should('have.length', 1)
            .click()
        cy.get('[data-testid="common-text-field"]')
            .eq(0)
            .click()
            .focus()
            .type("ABC")
        cy.get('[data-testid="common-text-field"]')
            .eq(1)
            .click()
            .focus()
            .type("1111111111111")
        cy.get('[data-testid="common-text-field"]')
            .eq(2)
            .click()
            .focus()
            .type("111111111")
        cy.get('[data-testid="common-text-field"]')
            .eq(3)
            .click()
            .focus()
            .type("12345")
        cy.get('[data-testid="common-text-field"]')
            .eq(4)
            .click()
            .focus()
            .type("test")
        cy.get('[data-testid="common-text-field"]')
            .eq(5)
            .click()
            .focus()
            .type("test")
        cy.get('[data-testid="common-button"]')
            .eq(2)
            .click()
        cy.get('.rnc__notification-content').should("have.length.at.least", 1).should('have.text', 'Uspesno ste uneli kompaniju')
    })

    it("company page => add new company => invalid text imput should show red outline", () => {
        cy.get('[data-testid="common-button"]')
            .should('have.length', 1)
            .click()
        cy.get('[data-testid="common-text-field"]')
            .eq(1)
            .click()
            .focus()
            .type("1111111")
            .should('have.class', 'outline-red-500')
    })

    it("company page => add new company => adding company with the same key should show an error", () => {
        cy.get('[data-testid="common-button"]')
            .should('have.length', 1)
            .click()
        cy.get('[data-testid="common-text-field"]')
            .eq(0)
            .click()
            .focus()
            .type("QWERTY")
        cy.get('[data-testid="common-text-field"]')
            .eq(1)
            .click()
            .focus()
            .type("1111111111111")
        cy.get('[data-testid="common-text-field"]')
            .eq(2)
            .click()
            .focus()
            .type("123456789")
        cy.get('[data-testid="common-text-field"]')
            .eq(3)
            .click()
            .focus()
            .type("11115")
        cy.get('[data-testid="common-text-field"]')
            .eq(4)
            .click()
            .focus()
            .type("test1")
        cy.get('[data-testid="common-text-field"]')
            .eq(5)
            .click()
            .focus()
            .type("serbia")
        cy.get('[data-testid="common-button"]')
            .eq(2)
            .click()
        cy.get('.rnc__notification-content').should("have.length.at.least", 1).should('have.text', "Doslo je do greske prilikom pravljenja kompanijeMolimo pokusajte opet.")
    })

    it("company page => table click => redirect to company's page", () => {
        cy.wait(500)
        cy.get('[data-testid="common-table-row"]')
            .should('have.length.at.least', 1)
            .eq(0)
            .click()
        cy.url().should("be.equal", `http://localhost:3000/${URLS.DASHBOARD.COMPANY.LIST}/ABC`);
    })

    it("company page => table click => update company", () => {
        cy.wait(500)
        cy.get('[data-testid="common-table-row"]')
            .should('have.length.at.least', 1)
            .eq(0)
            .click()
        cy.url().should("be.equal", `http://localhost:3000/${URLS.DASHBOARD.COMPANY.LIST}/ABC`);
        
        //TODO: izmeniti kompaniju (drzava)
    })

    it("company page => table click => bank account block => add bank account", () => {
        cy.wait(500)
        cy.get('[data-testid="common-table-row"]')
            .should('have.length.at.least', 1)
            .eq(0)
            .click()
        cy.url().should("be.equal", `http://localhost:3000/${URLS.DASHBOARD.COMPANY.LIST}/ABC`);
        cy.get('[data-testid="common-button"]')
            .should('have.length.at.least', 4)
            .eq(1)
            .click()
        cy.get('[data-testid="common-select"]').should('have.length', 1).select(10)
        cy.get('[data-testid="common-text-field"]')
            .eq(6)
            .click()
            .focus()
            .type("123456789")
        cy.get('[data-testid="common-text-field"]')
            .eq(7)
            .click()
            .focus()
            .type("Banka")
        cy.get('[data-testid="common-button"]')
            .eq(3)
            .click()
        cy.get('.rnc__notification-content').should("have.length.at.least", 1).should('have.text', 'Uspesno ste uneli racun')
    })

    it("company page => table click => bank account block => delete bank account", () => {
        cy.wait(500)
        cy.get('[data-testid="common-table-row"]')
            .should('have.length.at.least', 1)
            .eq(0)
            .click()
        cy.url().should("be.equal", `http://localhost:3000/${URLS.DASHBOARD.COMPANY.LIST}/ABC`);
        cy.get('[data-testid="common-table-row"]')
            .should('have.length.at.least', 1)
            .eq(0)
            .click()
        cy.get('[data-testid="common-button"]')
            .eq(2)
            .click()
        cy.get('.rnc__notification-content').should("have.length.at.least", 1).should('have.text', 'Uspesno ste obrisali racun')
    })

    it("company page => table click => agreement block => add agreement", () => {
        cy.wait(500)
        cy.get('[data-testid="common-table-row"]')
            .should('have.length.at.least', 1)
            .eq(0)
            .click()
        cy.url().should("be.equal", `http://localhost:3000/${URLS.DASHBOARD.COMPANY.LIST}/ABC`);
        cy.get('[data-testid="common-button"]')
            .should('have.length.at.least', 4)
            .eq(2)
            .click()
        cy.wait(100)
        cy.get('[data-testid="common-text-field"]')
            .eq(6)
            .click()
            .focus()
            .type("123")
        cy.get('[data-testid="common-textarea"]')
            .eq(0)
            .click()
            .focus()
            .type("test test")
        cy.get('[data-testid="common-button"]')
            .eq(4)
            .click()
        cy.get('.rnc__notification-content').should("have.length.at.least", 1).should('have.text', 'Uspesno ste kreirali ugovor')
    })

    it("company page => table click => agreement block => agreement table click => redirect to the agreement", () => {
        cy.wait(500)
        cy.get('[data-testid="common-table-row"]')
            .should('have.length.at.least', 1)
            .eq(0)
            .click()
        cy.url().should("be.equal", `http://localhost:3000/${URLS.DASHBOARD.COMPANY.LIST}/ABC`);
        cy.wait(500)
        cy.get('[data-testid="common-table-row"]')
            .should('have.length.at.least', 1)
            .eq(0)
            .click()
        cy.url().should("be.equal", `http://localhost:3000/${URLS.DASHBOARD.AGREEMENT.LIST}/1`);
    })

    it("company page => table click => agreement block => agreement table click => change the description", () => {
        cy.wait(500)
        cy.get('[data-testid="common-table-row"]')
            .should('have.length.at.least', 1)
            .eq(0)
            .click()
        cy.url().should("be.equal", `http://localhost:3000/${URLS.DASHBOARD.COMPANY.LIST}/ABC`);
        cy.wait(500)
        cy.get('[data-testid="common-table-row"]')
            .should('have.length.at.least', 1)
            .eq(0)
            .click()
        cy.get('[data-testid="common-textarea"]')
            .eq(0)
            .click()
            .focus()
            .clear()
            .type("test test test")
        cy.get('[data-testid="common-button"]')
            .should('have.length.at.least', 4)
            .eq(1)
            .click()
        cy.get('.rnc__notification-content').should("have.length.at.least", 1).should('have.text', 'Uspesno ste izmenili ugovor.')
    })

    it("company page => table click => contact block => add contact", () => {
        cy.wait(500)
        cy.get('[data-testid="common-table-row"]')
            .should('have.length.at.least', 1)
            .eq(0)
            .click()
        cy.url().should("be.equal", `http://localhost:3000/${URLS.DASHBOARD.COMPANY.LIST}/ABC`);
        cy.get('[data-testid="common-button"]')
            .eq(2)
            .click()
        cy.get('[data-testid="common-text-field"]')
            .eq(6)
            .click()
            .focus()
            .type("Petar")
        cy.get('[data-testid="common-text-field"]')
            .eq(7)
            .click()
            .focus()
            .type("Petrovic")
        cy.get('[data-testid="common-text-field"]')
            .eq(8)
            .click()
            .focus()
            .type("test@email.com")
        cy.get('[data-testid="common-text-field"]')
            .eq(9)
            .click()
            .focus()
            .type("123456789")
        cy.get('[data-testid="common-text-field"]')
            .eq(10)
            .click()
            .focus()
            .type("admin")
        cy.get('[data-testid="common-text-field"]')
            .eq(11)
            .click()
            .focus()
            .type("test test")
        cy.get('[data-testid="common-button"]')
            .eq(5)
            .click()
        cy.get('.rnc__notification-content').should("have.length.at.least", 1).should('have.text', 'Uspesno ste uneli kontakt osobu')
    })

    it("company page => table click => contact block => delete contact", () => {
        cy.wait(500)
        cy.get('[data-testid="common-table-row"]')
            .should('have.length.at.least', 1)
            .eq(0)
            .click()
        cy.url().should("be.equal", `http://localhost:3000/${URLS.DASHBOARD.COMPANY.LIST}/ABC`);
        cy.wait(500)
        cy.get('[data-testid="common-table-row"]')
            .eq(1)
            .click()
        cy.get('[data-testid="common-button"]')
            .eq(4)
            .click()
        cy.get('.rnc__notification-content').should("have.length.at.least", 1).should('have.text', 'Uspesno ste obrisali kontakt')
    })
});