import React from "react";
import QRCode from "react-qr-code";

import Modal from "./Modal";

export default {
    title: "Common/Modal",
    component: Modal,
    argTypes: {
    },
};

const Template = (args) => (
    <div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Viverra accumsan in nisl nisi scelerisque. Amet consectetur adipiscing elit duis. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Urna duis convallis convallis tellus id interdum velit. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Habitant morbi tristique senectus et netus et malesuada fames. Proin sagittis nisl rhoncus mattis rhoncus urna. Proin fermentum leo vel orci porta non pulvinar.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Viverra accumsan in nisl nisi scelerisque. Amet consectetur adipiscing elit duis. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Urna duis convallis convallis tellus id interdum velit. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Habitant morbi tristique senectus et netus et malesuada fames. Proin sagittis nisl rhoncus mattis rhoncus urna. Proin fermentum leo vel orci porta non pulvinar.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Viverra accumsan in nisl nisi scelerisque. Amet consectetur adipiscing elit duis. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Urna duis convallis convallis tellus id interdum velit. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Habitant morbi tristique senectus et netus et malesuada fames. Proin sagittis nisl rhoncus mattis rhoncus urna. Proin fermentum leo vel orci porta non pulvinar.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Viverra accumsan in nisl nisi scelerisque. Amet consectetur adipiscing elit duis. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Urna duis convallis convallis tellus id interdum velit. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Habitant morbi tristique senectus et netus et malesuada fames. Proin sagittis nisl rhoncus mattis rhoncus urna. Proin fermentum leo vel orci porta non pulvinar.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Viverra accumsan in nisl nisi scelerisque. Amet consectetur adipiscing elit duis. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Urna duis convallis convallis tellus id interdum velit. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Habitant morbi tristique senectus et netus et malesuada fames. Proin sagittis nisl rhoncus mattis rhoncus urna. Proin fermentum leo vel orci porta non pulvinar.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Viverra accumsan in nisl nisi scelerisque. Amet consectetur adipiscing elit duis. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Urna duis convallis convallis tellus id interdum velit. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Habitant morbi tristique senectus et netus et malesuada fames. Proin sagittis nisl rhoncus mattis rhoncus urna. Proin fermentum leo vel orci porta non pulvinar.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Viverra accumsan in nisl nisi scelerisque. Amet consectetur adipiscing elit duis. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Urna duis convallis convallis tellus id interdum velit. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Habitant morbi tristique senectus et netus et malesuada fames. Proin sagittis nisl rhoncus mattis rhoncus urna. Proin fermentum leo vel orci porta non pulvinar.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Viverra accumsan in nisl nisi scelerisque. Amet consectetur adipiscing elit duis. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Urna duis convallis convallis tellus id interdum velit. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Habitant morbi tristique senectus et netus et malesuada fames. Proin sagittis nisl rhoncus mattis rhoncus urna. Proin fermentum leo vel orci porta non pulvinar.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Viverra accumsan in nisl nisi scelerisque. Amet consectetur adipiscing elit duis. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Urna duis convallis convallis tellus id interdum velit. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Habitant morbi tristique senectus et netus et malesuada fames. Proin sagittis nisl rhoncus mattis rhoncus urna. Proin fermentum leo vel orci porta non pulvinar.</p>
        <Modal visible={true} {...args} />
    </div>

);

const defaultChildren = (
    <div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Viverra accumsan in nisl nisi scelerisque. Amet consectetur adipiscing elit duis. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Urna duis convallis convallis tellus id interdum velit. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Habitant morbi tristique senectus et netus et malesuada fames. Proin sagittis nisl rhoncus mattis rhoncus urna. Proin fermentum leo vel orci porta non pulvinar.</p>
    </div>
)

export const Default = Template.bind({});
Default.args = {
    id: 'storyModal',
    title: 'Title',
    children: defaultChildren,
};

export const WithCta = Template.bind({});
WithCta.args = {
    id: 'storyModal',
    title: 'Title',
    children: defaultChildren,
    cta: () => { },
};

const longChildren = (
    <div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Viverra accumsan in nisl nisi scelerisque. Amet consectetur adipiscing elit duis. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Urna duis convallis convallis tellus id interdum velit. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Habitant morbi tristique senectus et netus et malesuada fames. Proin sagittis nisl rhoncus mattis rhoncus urna. Proin fermentum leo vel orci porta non pulvinar.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Viverra accumsan in nisl nisi scelerisque. Amet consectetur adipiscing elit duis. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Urna duis convallis convallis tellus id interdum velit. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Habitant morbi tristique senectus et netus et malesuada fames. Proin sagittis nisl rhoncus mattis rhoncus urna. Proin fermentum leo vel orci porta non pulvinar.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Viverra accumsan in nisl nisi scelerisque. Amet consectetur adipiscing elit duis. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Urna duis convallis convallis tellus id interdum velit. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Habitant morbi tristique senectus et netus et malesuada fames. Proin sagittis nisl rhoncus mattis rhoncus urna. Proin fermentum leo vel orci porta non pulvinar.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Viverra accumsan in nisl nisi scelerisque. Amet consectetur adipiscing elit duis. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Urna duis convallis convallis tellus id interdum velit. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Habitant morbi tristique senectus et netus et malesuada fames. Proin sagittis nisl rhoncus mattis rhoncus urna. Proin fermentum leo vel orci porta non pulvinar.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Viverra accumsan in nisl nisi scelerisque. Amet consectetur adipiscing elit duis. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Urna duis convallis convallis tellus id interdum velit. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Habitant morbi tristique senectus et netus et malesuada fames. Proin sagittis nisl rhoncus mattis rhoncus urna. Proin fermentum leo vel orci porta non pulvinar.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Viverra accumsan in nisl nisi scelerisque. Amet consectetur adipiscing elit duis. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Urna duis convallis convallis tellus id interdum velit. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Habitant morbi tristique senectus et netus et malesuada fames. Proin sagittis nisl rhoncus mattis rhoncus urna. Proin fermentum leo vel orci porta non pulvinar.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Viverra accumsan in nisl nisi scelerisque. Amet consectetur adipiscing elit duis. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Urna duis convallis convallis tellus id interdum velit. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Habitant morbi tristique senectus et netus et malesuada fames. Proin sagittis nisl rhoncus mattis rhoncus urna. Proin fermentum leo vel orci porta non pulvinar.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Viverra accumsan in nisl nisi scelerisque. Amet consectetur adipiscing elit duis. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Urna duis convallis convallis tellus id interdum velit. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Habitant morbi tristique senectus et netus et malesuada fames. Proin sagittis nisl rhoncus mattis rhoncus urna. Proin fermentum leo vel orci porta non pulvinar.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Viverra accumsan in nisl nisi scelerisque. Amet consectetur adipiscing elit duis. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Urna duis convallis convallis tellus id interdum velit. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Habitant morbi tristique senectus et netus et malesuada fames. Proin sagittis nisl rhoncus mattis rhoncus urna. Proin fermentum leo vel orci porta non pulvinar.</p>
    </div>
)

export const Long = Template.bind({});
Long.args = {
    id: 'storyModal',
    title: 'Title',
    children: longChildren,
};

const qrCodeChildren = (
    <div>
        <p>Scan QR code</p>
        <div className="flex justify-center my-5">
            <QRCode value="Generating QR code is easy with react-qr-code, you just need some text." />
        </div>
    </div>
)
export const QrCode = Template.bind({});
QrCode.args = {
    id: 'storyModal',
    title: 'Title',
    children: qrCodeChildren,
};